"use strict";
exports.__esModule = true;
exports.goodsManager1 = void 0;
var goods_1 = require("./goods");
var goodsmanager_1 = require("./goodsmanager");
exports.goodsManager1 = new goodsmanager_1.Goodsmanager();
var goods = new goods_1.Goods(1, "Quan", "Quan ao", 100, 500, "San pham quan jean di choi, di hoc dang cao");
var goods1 = new goods_1.Goods(2, "Ao thun", "Quan ao", 200, 600, "San pham ao thun day dan");
var goods2 = new goods_1.Goods(3, "Banh", "Thuc pham", 50, 1000, "Banh osi nhap tu han quoc bao ngon gia re");
var goods3 = new goods_1.Goods(4, "Keo", "Thuc pham", 100, 700, "Keo dua mien tay sieu dinh ");
var goods4 = new goods_1.Goods(5, "Son ", "Mi pham", 700, 1000, "Son moi li, khong troi it chi");
var goods5 = new goods_1.Goods(6, "Phan", "Mi pham", 200, 500, "Phan che khuyet điem hang sieu hot, che mo vet tham");
var goods6 = new goods_1.Goods(7, "Nhan", "Trang suc", 600, 500, "Nhan bac con gau de thuong");
exports.goodsManager1.add(goods);
exports.goodsManager1.add(goods1);
exports.goodsManager1.add(goods2);
exports.goodsManager1.add(goods3);
exports.goodsManager1.add(goods4);
exports.goodsManager1.add(goods5);
exports.goodsManager1.add(goods6);
